services:
  labsync:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - labsync_data:/app/data
    environment:
      - SECRET_KEY=${SECRET_KEY:-LABSYNC_SUPER_SECRET_KEY_ENTERPRISE_7.0}
      - LICENSE_GITHUB_TOKEN=${LICENSE_GITHUB_TOKEN:?Variable LICENSE_GITHUB_TOKEN requerida}
      - DATABASE_URL=sqlite:///app/data/labsync.db
      - LLAMA_PORT=8080
    restart: unless-stopped

volumes:
  labsync_data:
