platform :ios, '12.0'

target 'Runner' do
  use_frameworks!
  pod 'sqflite', :path => '.symlinks/plugins/sqflite/ios'
  pod 'shared_preferences_ios', :path => '.symlinks/plugins/shared_preferences_ios/ios'
  pod 'path_provider_ios', :path => '.symlinks/plugins/path_provider_ios/ios'
end
