name: Build LABSYNC

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - run: flutter pub get

      - run: flutter build windows --dart-define=LICENSE_GITHUB_TOKEN=${{ secrets.LICENSE_GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: labsync-windows
          path: build/windows/
